// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovinMeyar.Customer.DataLayer;

namespace NovinMeyar.Customer.Api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220807185125_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NovinMeyar.Customer.Domain.Entities.LegalCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CEOBirthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CEOCell")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CEOFirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CEOLastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("EconomicCode")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RegisterNo")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TellPhone")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserCreatorName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserModifiedName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("LegalCustomers");
                });

            modelBuilder.Entity("NovinMeyar.Customer.Domain.Entities.RealCustomer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<string>("CellPhone")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExteraInformation")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("NationalCartId")
                        .HasColumnType("bigint");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TellPhone")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserCreatorName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UserModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserModifiedName")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RealCustomers");
                });

            modelBuilder.Entity("NovinMeyar.Domain.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuditAction")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("AuditDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AuditUser")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TablePK")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
