<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <Configurations>Debug;Release;USEKestrel;KESTREL</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\MessageBroker\NovinMeyar.MessageBroker.ShareModels\NovinMeyar.Common.csproj" />
  </ItemGroup>

</Project>
